const mongoose = require('mongoose');

const PrescriptionSchema = new mongoose.Schema({
  patientId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  doctorId: { type: mongoose.Schema.Types.ObjectId, ref: 'Doctor', required: true },
  storeId: { type: mongoose.Schema.Types.ObjectId, ref: 'Store', required: true },
  tokenId: { type: mongoose.Schema.Types.ObjectId, ref: 'Token' },

  type: {
    type: String,
    enum: ["prescription", "consultation"],
    default: "prescription"
  },

  // Auto-generated by Gemini
  heading: { type: String, default: "" },

  medicines: [{
    drug: { type: String, required: true },
    dose: { type: String },
    frequency: { type: String },
    duration: { type: String },
    instructions: { type: String },
  }],

  clinicalNotes: { type: String, default: "" },
  rawText: { type: String }, // For debugging/audit

  strokeData: [{
    rowNumber: Number,
    strokes: String,  // JSON stringified array of {x, y, t, p}
  }],

  status: {
    type: String,
    enum: ["draft", "confirmed"],
    default: "draft"
  },
}, { timestamps: true });

// Optimize queries for the 3 main views
PrescriptionSchema.index({ patientId: 1, createdAt: -1 });
PrescriptionSchema.index({ storeId: 1, createdAt: -1 });
PrescriptionSchema.index({ doctorId: 1, createdAt: -1 });

module.exports = mongoose.model('Prescription', PrescriptionSchema);
